[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    mikalhart/TinyGPSPlus@^1.0.3
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/Adafruit HMC5883 Unified@^1.2.1
    bblanchon/ArduinoJson@^6.21.3
board_build.partitions = default.csv
